export const questions = [
  '¿Cuándo es adecuado acudir a un psicólogo?',
  '¿Cuánto tiempo dura una terapia?',
  '¿Cuántas veces tengo que ir?',
  '¿Puedo conseguir un descuento si mi terapia es larga?',
  '¿Todo lo que diga al psicólogo es privado?',
  'Si hay algo que no me apetece hablar de ello ¿qué pasa si me lo callo?',
  '¿Necesita el psicólogo hablar también con alguien de mi familia o cercano?',
  '¿Si he acabado la terapia hace un tiempo, pero me ocurre algo muy puntual y necesito consultar, puedo ir aunque solo sea una sesión?',
  '¿Cómo puedo explicarle a mi hijo que vaya al psicólogo?',
  'Soy una persona con mucho miedo a salir a la calle sola, me gustaría hacer terapia pero me han dicho que tengo luego que salir a la calle sola ¿es así?',
  '¿Qué son las sesiones de seguimiento?',
  '¿Es siempre imprescindible el seguimiento?',
  '¿Si ya estoy bien puedo seguir yendo al psicólogo?',
  '¿Siempre iré con el mismo psicólogo?',
  '¿Qué pasa si me pongo malo y no puedo ir?',
  '¿Qué es terapia cognitivo conductual?',
  '¿ La terapia podrá ayudarme con mi problema?',
  'He leído que hay que hacer tareas para casa ¿son fáciles y requieren de mucho tiempo?',
  '¿Cuándo pago las sesiones?'
];

export const answers = [
  'Hay momentos en nuestra vida que nos sentimos diferentes, más vulnerables o más irascibles, o bien pasamos por momentos que no somos capaces de afrontar adecuadamente y nos causa un gran malestar o angustia, o tal vez hay situaciones que siempre hemos evitado y queremos de una vez por todas poner soluciones, también puede pasar sencillamente que tengamos dudas de cómo afrontar una situación y necesitemos una orientación, cualquiera de estos momentos son idóneos para solicitar ayuda profesional. Es importante tener en cuenta que cuando demoramos pedir apoyo profesional puede tener como consecuencia el agravamiento del malestar que sentimos.',
  'La duración de una terapia dependerá de muchos factores, como por ejemplo la persona a tratar, el problema a tratar, los objetivos a alcanzar con dicha persona, la cronicidad del problema, la demanda de la persona y la implicación de la persona en la terapia. Si podemos afirmar, que en la mayoría de los casos, se suelen empezar a ver resultados a partir de llevar 10-12 sesiones.',
  'Para que la terapia sea efectiva, las sesiones se realizan una vez a la semana. Algunos tratamientos pueden necesitar una frecuencia mayor, 2 sesiones a la semana, en otros casos será suficiente una sesión cada quince días.',
  'Las tarifas por sesiones individuales son siempre las mismas, independientemente de la duración de la terapia. Si bien es cierto que aplicamos descuentos en casos especiales, la duración de la terapia no es un caso especial para aplicar descuento. Consulta nuestras tarifas especiales.',
  'Indudablemente, es un principio fundamental en el proceso psicológico, disfrutarás de auténtica confidencialidad.',
  'Es totalmente normal que a veces no nos apetezca hablar de cosas que no nos gustan o no nos sentimos bien hablando de ellas. Puedes omitirlas, ya que la persona tiene derecho a preservar su intimidad, pero te recomendamos que trates de hablar de ello, ya que probablemente notaras un gran alivio a la vez que servirá para que el psicólogo te pueda ayudar mejor. Tú serás quien lo decida, has de tener en cuenta que en ningún momento el psicólogo te juzgara.',
  'Hay veces, que es recomendable que algún familiar o persona allegada pueda venir a visitarnos con el fin de poder adquirir mayor información, o simplemente para asesorarles de los beneficios que puede obtener si cambia algo que consideramos no es adecuado que realice, y de esta manera conseguir los objetivos planteados en la terapia. No obstante siempre contaremos con el visto bueno tuyo y si no quisieras no se realizaría.',
  'Sin duda, puedes de nuevo llamarnos y pedirnos cita y por supuesto pasarás sesión con el mismo psicólogo que te atendió.',
  'Si es verdad que existen muchos prejuicios a la hora de ir al psicólogo, si bien en los adultos parece que ya no existe tanto , en los niños a veces pueden generarles dudas de porque ellos tienen que ir. Sin embargo puedes ponerle el ejemplo de que los niños van al médico no solo cuando están enfermos, sino también acuden para una revisión rutinaria o para vacunarse y evitar enfermedades, así mismo ir al psicólogo no supone “ser raro” sino es un profesional que te ayudará a manejar situaciones que te pueden llegar a causar malestar sino aprendes a manejarlas adecuadamente.',
  'En principio durante la terapia se irán marcando los objetivos a conseguir, es probable que el salir a la calle sea uno de los objetivos marcados ya que sin duda es lo que quieres llegar a conseguir, no obstante en las primeras ocasiones que te expongas no irías sola, contarías con el acompañamiento de tu psicólogo o una persona adecuada para ello. Este acompañamiento en la mayoría de las ocasiones se realiza de una forma gratuita.',
  'Las sesiones de seguimiento son aquellas que se realizan cuando la persona ha alcanzado los objetivos que buscaba con la terapia .Se suele empezar haciendo dos sesiones al mes y luego una al mes. En ellas se valoran la eficacia de la terapia y la persona observa cómo ha interiorizado todo lo aprendido. Es una etapa más dentro de la terapia y muy recomendable realizarlas, pero serán el psicólogo y el paciente conjuntamente los que decidan cuantas hacer. Hay casos en que la propia persona decide hacer más, y mantener una al mes durante el tiempo que precise.',
  'Es muy recomendable llevarlo a cabo, además es una etapa que forma parte de la terapia.',
  'En la mayoría de los casos, las personas cuando se sienten bien y una vez acabado el seguimiento tienden a dar por finalizada la terapia, no obstante si alguna persona necesitará o quisiera seguir viniendo, por supuesto puede seguir viniendo y seguir trabajando. Siempre realizará las sesiones con el mismo psicólogo.',
  'Sí, siempre realizarás la terapia con el mismo psicólogo.',
  'No pasa nada, si bien es verdad que es importante la continuidad de la terapia para la eficacia de la misma. No obstante, si fuera necesario, realizaríamos la sesión por skype.',
  'La terapia cognitivo conductual es un tipo de orientación basada en el presente actual de la persona. Se tienen en cuenta aspectos del pasado para poder entender pensamientos, emociones, y conductas que se realizan en el presente y poder así aprender a modificarlas. El objetivo principal es que la persona adquiera herramientas, habilidades y las estrategias necesarias para poder resolver aquellas situaciones que le generan malestar o angustia. Es una terapia activa, donde se incluyen tareas sencillas para realizar. La terapia es de corta duración en comparación con otras orientaciones de terapia. La terapia cognitivo conductual goza de gran eficacia en los tratamientos psicológicos.',
  'Siempre dependerá de cuál sea tu problema concreto. En ocasiones nos encontramos con problemas que podemos abordar en su totalidad, es decir, el malestar remitirá totalmente, pero también hay otras veces donde hay problemas cuyo objetivo es disminuir dicho malestar, es decir, aprender a reducir el malestar cuando aparezca, ya que aprenderemos a conocer y detectar que nos pasa y cuando, y sabremos enfrentarnos a ello y manejarlo.',
  'Si, sin duda son tareas fáciles de realizar que además aprenderás con el psicólogo. Te servirán para ir poniendo en práctica todo lo aprendido en la sesión. No, no te llevaran demasiado tiempo el hacerlas.',
  'Las sesiones se abonan al acabar cada sesión'
];